# ==============================================================================
# FinTechFlow - Infrastructure as Code (Terraform)
# ==============================================================================
# Educational Demonstration:
#   This Terraform configuration models the cloud infrastructure provisioning
#   for the FinTechFlow application (VPC, Subnets, Container Services, Load
#   Balancer, and Blue-Green Routing State) in an automated, cost-free manner.
# ==============================================================================

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
  }
}

# Unique deployment ID for zero-collision resource naming
resource "random_id" "deployment_id" {
  byte_length = 4
}

locals {
  service_name = lower("${var.app_name}-${var.environment}-${random_id.deployment_id.hex}")

  # Conceptual Infrastructure Topology
  vpc_cidr = "10.0.0.0/16"
  subnets = {
    public_a  = "10.0.1.0/24"
    public_b  = "10.0.2.0/24"
    private_a = "10.0.10.0/24"
    private_b = "10.0.20.0/24"
  }

  active_port = var.active_traffic_slot == "blue" ? var.blue_slot_port : var.green_slot_port

  manifest_content = jsonencode({
    deployment = {
      service_name        = local.service_name
      app_name            = var.app_name
      app_version         = var.app_version
      environment         = var.environment
      active_slot         = var.active_traffic_slot
      active_routing_port = local.active_port
      container_port      = var.container_port
      health_check_path   = "/health"
      metrics_path        = "/metrics"
    }
    network = {
      vpc_cidr = local.vpc_cidr
      subnets  = local.subnets
    }
    blue_green_slots = {
      blue = {
        name    = "slot-blue-production"
        port    = var.blue_slot_port
        status  = var.active_traffic_slot == "blue" ? "LIVE_TRAFFIC" : "STANDBY"
        version = var.active_traffic_slot == "blue" ? var.app_version : "1.0.0-previous"
      }
      green = {
        name    = "slot-green-candidate"
        port    = var.green_slot_port
        status  = var.active_traffic_slot == "green" ? "LIVE_TRAFFIC" : "CANDIDATE_VALIDATION"
        version = var.app_version
      }
    }
  })
}

# Generates the Infrastructure Environment Manifest for Container Orchestration
resource "local_file" "environment_manifest" {
  filename = "${path.module}/generated_infra_manifest.json"
  content  = local.manifest_content
}

# Generates Container Runtime Configuration for Staging/Production
resource "local_file" "runtime_env_file" {
  filename = "${path.module}/generated_runtime.env"
  content  = <<-EOT
    # Auto-generated by Terraform Infrastructure as Code
    # Environment: ${var.environment}
    # Active Traffic Slot: ${var.active_traffic_slot}
    APP_NAME=${var.app_name}
    APP_VERSION=${var.app_version}
    ENVIRONMENT=${var.environment}
    PORT=${var.container_port}
    ACTIVE_SLOT_PORT=${local.active_port}
    LOG_LEVEL=INFO
    ENABLE_METRICS=${var.enable_observability}
  EOT
}
